In [7]:
import pandas as pd
import numpy as np

Data_Listings = pd.read_csv('listings.csv')
# print(Data_Listings)
# print(Data_Listings.head())
# print(Data_Listings.tail())
print(Data_Listings.describe())
#Data_Listings.iat[4, 4] = np.nan
#print(Data_Listings.describe())
#Data_Listings_Dropna = Data_Listings.dropna()
Data_Listings_Fill = Data_Listings.fillna(0)
#print(Data_Listings_Dropna.describe())
Data_Listings_Fill.describe()

                 id       host_id  neighbourhood_group  neighbourhood
count  3.161000e+03  3.161000e+03                  0.0    3161.000000  \
mean   1.755521e+17  1.427008e+08                  NaN   28792.496362
std    3.046268e+17  1.404253e+08                  NaN      30.506506
min    1.080610e+05  1.504900e+04                  NaN   28704.000000
25%    2.506879e+07  2.574990e+07                  NaN   28801.000000
50%    4.401835e+07  9.630593e+07                  NaN   28804.000000
75%    5.499785e+17  2.066904e+08                  NaN   28806.000000
max    8.493220e+17  5.048949e+08                  NaN   28806.000000

          latitude    longitude        price  minimum_nights
count  3161.000000  3161.000000  3161.000000     3161.000000  \
mean     35.576571   -82.558173   175.025941        5.197722
std       0.049050     0.047981   187.788697       10.503005
min      35.422810   -82.691050    10.000000        1.000000
25%      35.561020   -82.592430    92.000000        1.000000
50%      35.587510   -82.557380   130.000000        2.000000
75%      35.606120   -82.521950   204.000000        2.000000
max      35.656090   -82.459420  6588.000000      180.000000

       number_of_reviews  reviews_per_month  calculated_host_listings_count
count        3161.000000        2918.000000                     3161.000000  \
mean           95.489402           2.596542                        8.674154
std           125.547268           2.160669                       22.411573
min             0.000000           0.010000                        1.000000
25%            10.000000           0.990000                        1.000000
50%            48.000000           2.070000                        2.000000
75%           134.000000           3.620000                        4.000000
max          1156.000000          14.660000                      115.000000

       availability_365  number_of_reviews_ltm  license
count       3161.000000            3161.000000      0.0
mean         204.468206              23.746916      NaN
std          118.527579              25.702765      NaN
min            0.000000               0.000000      NaN
25%           95.000000               3.000000      NaN
50%          224.000000              16.000000      NaN
75%          316.000000              36.000000      NaN
max          365.000000             181.000000      NaN

,id,host_id,neighbourhood_group,neighbourhood,latitude,longitude,price,minimum_nights,number_of_reviews,reviews_per_month,calculated_host_listings_count,availability_365,number_of_reviews_ltm,license
count,3.161000e+03,3.161000e+03,3161.0,3161.000000,3161.000000,3161.000000,3161.000000,3161.000000,3161.000000,3161.000000,3161.000000,3161.000000,3161.000000,3161.0
mean,1.755521e+17,1.427008e+08,0.0,28792.496362,35.576571,-82.558173,175.025941,5.197722,95.489402,2.396935,8.674154,204.468206,23.746916,0.0
std,3.046268e+17,1.404253e+08,0.0,30.506506,0.049050,0.047981,187.788697,10.503005,125.547268,2.188170,22.411573,118.527579,25.702765,0.0
min,1.080610e+05,1.504900e+04,0.0,28704.000000,35.422810,-82.691050,10.000000,1.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.0
25%,2.506879e+07,2.574990e+07,0.0,28801.000000,35.561020,-82.592430,92.000000,1.000000,10.000000,0.680000,1.000000,95.000000,3.000000,0.0
50%,4.401835e+07,9.630593e+07,0.0,28804.000000,35.587510,-82.557380,130.000000,2.000000,48.000000,1.880000,2.000000,224.000000,16.000000,0.0
75%,5.499785e+17,2.066904e+08,0.0,28806.000000,35.606120,-82.521950,204.000000,2.000000,134.000000,3.470000,4.000000,316.000000,36.000000,0.0
max,8.493220e+17,5.048949e+08,0.0,28806.000000,35.656090,-82.459420,6588.000000,180.000000,1156.000000,14.660000,115.000000,365.000000,181.000000,0.0